docs: Added fields for 1.0 invoke transaction
starknet-community-libs/starknet-docs pull request #53
Opened 2022-08-15 09:45 UTC by stoobie

### Description of the Changes

Enhancement: New fields for version 1.0 `invoke` transaction.

2022-08-17 08:39 UTC, stoobie commented
@ArielElp Please review.

2022-08-18 06:23 UTC, bbrandtom requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`docs/Blocks/transactions.md` line 60 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jafAS8zp6RNETelDY:-N9jafAT7cFG_CY0htA2:undefined) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L60)):*
> ```Markdown
> | -------------------------- | :------------------------------: | -------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
> | `contract_address`         |                0                 | `FieldElement`       | The address of the contract invoked by this transaction.                                                                                                                                                                                                                                                                                               |
> | `account_contract_address` |                1                 | `FieldElement`       | The address of the contract invoked by this transaction.                                                                                                                                                                                                                                                                                               |
> ```





_Suggestion:_
```Markdown
The address of the sender of this transaction.
```
___
*[`docs/Blocks/transactions.md` line 60 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jbIMD-5sGB4qFJZXF:-N9jbIMD-5sGB4qFJZXG:b-mua1ko) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L60)):*
> ```Markdown
> | -------------------------- | :------------------------------: | -------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
> | `contract_address`         |                0                 | `FieldElement`       | The address of the contract invoked by this transaction.                                                                                                                                                                                                                                                                                               |
> | `account_contract_address` |                1                 | `FieldElement`       | The address of the contract invoked by this transaction.                                                                                                                                                                                                                                                                                               |
> ```

In the declare transaction we call this field `sender_address`. I think we should be consistent, and I prefer `sender_address`.
@arielelp wdyt? How is this called in the JSON-RPC spec?



_Code quote:_
```Markdown
| `account_contract_address` | 
```
___
*[`docs/Blocks/transactions.md` line 62 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jam4N9xE6x-MNmsAM:-N9jam4N9xE6x-MNmsAN:bksnvx8) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L62)):*
> ```Markdown
> | `account_contract_address` |                1                 | `FieldElement`       | The address of the contract invoked by this transaction.                                                                                                                                                                                                                                                                                               |
> | `entry_point_selector`     |                0                 | `FieldElement`       | The encoding of the selector for the function invoked (the entry point in the contract)                                                                                                                                                                                                                                                                |
> | `calldata`                 |               0, 1               | `List<FieldElement>` | The arguments passed to the invoked function                                                                                                                                                                                                                                                                                                           |
> ```

This is actually differnet in each version.
In version 0 it is the args that are passed to the invoked unction.
In version 1 it is the args that are passed to `validate` and to `execute`

Maybe we should consider having to different tables.



_Code quote:_
```Markdown
The arguments passed to the invoked function
```
___
*[`docs/Blocks/transactions.md` line 63 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jb2RzAyse3I0eGb3f:-N9jb2RzAyse3I0eGb3g:undefined) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L63)):*
> ```Markdown
> | `entry_point_selector`     |                0                 | `FieldElement`       | The encoding of the selector for the function invoked (the entry point in the contract)                                                                                                                                                                                                                                                                |
> | `calldata`                 |               0, 1               | `List<FieldElement>` | The arguments passed to the invoked function                                                                                                                                                                                                                                                                                                           |
> | `signature`                |               0,1                | `List<FieldElement>` | Additional information given by the caller, representing the signature of the transaction                                                                                                                                                                                                                                                              |
> ```





_Suggestion:_
```Markdown
sender, used to validate the transaction
```
___
*[`docs/Blocks/transactions.md` line 65 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jaT9oCSP9-Ng25EIE:-N9jaT9oCSP9-Ng25EIF:b-8orfn7) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L65)):*
> ```Markdown
> | `signature`                |               0,1                | `List<FieldElement>` | Additional in [...]

2022-08-18 15:46 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)

___
*[`docs/Blocks/transactions.md` line 60 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jafAS8zp6RNETelDY:-N9lasc91qdoLfqAodQf:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L60)):*
> ```Markdown
> | -------------------------- | :------------------------------: | -------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
> | `contract_address`         |                0                 | `FieldElement`       | The address of the contract invoked by this transaction.                                                                                                                                                                                                                                                                                               |
> | `account_contract_address` |                1                 | `FieldElement`       | The address of the contract invoked by this transaction.                                                                                                                                                                                                                                                                                               |
> ```

Done.
___
*[`docs/Blocks/transactions.md` line 60 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jbIMD-5sGB4qFJZXF:-N9law75-SkgtLuFZ9VD:b-6wspfs) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L60)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

In the declare transaction we call this field `sender_address`. I think we should be consistent, and I prefer `sender_address`.
@arielelp wdyt? How is this called in the JSON-RPC spec?
</blockquote></details>

@arielElp Awaiting your input.
___
*[`docs/Blocks/transactions.md` line 63 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jb2RzAyse3I0eGb3f:-N9lbMHw5PoqqP8p-Rxv:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L63)):*
> ```Markdown
> | `entry_point_selector`     |                0                 | `FieldElement`       | The encoding of the selector for the function invoked (the entry point in the contract)                                                                                                                                                                                                                                                                |
> | `calldata`                 |               0, 1               | `List<FieldElement>` | The arguments passed to the invoked function                                                                                                                                                                                                                                                                                                           |
> | `signature`                |               0,1                | `List<FieldElement>` | Additional information given by the caller, representing the signature of the transaction                                                                                                                                                                                                                                                              |
> ```

Done.
___
*[`docs/Blocks/transactions.md` line 66 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jaFP9Dh2GVBH01fDS:-N9lbre6DqP1QbOhNfRY:b-tk8m9i) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L66)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

this repeats the next section. I think it should be either here or in the next section, but not on both.
</blockquote></details>

This is applicable to any transaction with this parameter, and we shouldn't assume that someone will read the entire page. Each transaction description on this page should be treated as a standalone piece of content. This was in a footnote, but that's not as user-friendly. Why not just provide the information where it's useful?
___
*[`docs/Blocks/transactions.md` line 111 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jbcFC748dTqpCbVVs:-N9lcU-B1XIRMMbelSg8:bqv9vms) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L111)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

repeats the data from above. We should take it out to a separate section.
</blockquote></details>

I addressed this above. I don't think that's good for the reader.


<!-- Sent from Reviewable.io -->

2022-08-21 10:33 UTC, bbrandtom reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: all files reviewed, 6 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`docs/Blocks/transactions.md` line 66 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jaFP9Dh2GVBH01fDS:-N9zxc4fClqTTYrvE1fr:b-8fx2u7) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L66)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

This is applicable to any transaction with this parameter, and we shouldn't assume that someone will read the entire page. Each transaction description on this page should be treated as a standalone piece of content. This was in a footnote, but that's not as user-friendly. Why not just provide the information where it's useful?
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2022-08-21 11:34 UTC, ArielElp requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: all files reviewed, 12 unresolved discussions (waiting on @bbrandtom and @stoobie)

___
*[`docs/Blocks/transactions.md` line 60 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jbIMD-5sGB4qFJZXF:-NA-8GM9ByFL37iWQdXW:bu86lxj) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L60)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

@arielElp Awaiting your input.
</blockquote></details>

Agreed, but we should move to this terminology in the feeder gateway as well
___
*[`docs/Blocks/transactions.md` line 49 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-AUlO-E4WzdMk8BX4:-NA-AUlO-E4WzdMk8BX5:b-gvl79n) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/447fd62513b83e21eaec598ac735d48c25b4fc10/docs/Blocks/transactions.md#L49)):*
> ```Markdown
> - `contract_address` is calculated as described [here](../Contracts/contract-address.md).
> 
> ## Invoke Transaction
> ```

we need to add a warning/info that invoke v0 will be deprecated in future StarkNet versions



_Code quote:_
```Markdown
Invoke Transaction
```
___
*[`docs/Blocks/transactions.md` line 59 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-7fIb8gaIbYkrTvxl:-NA-7fIb8gaIbYkrTvxm:b-52u8wj) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/447fd62513b83e21eaec598ac735d48c25b4fc10/docs/Blocks/transactions.md#L59)):*
> ```Markdown
> | Name                       | Supported in transaction version | Type                 | Description                                                                                                                                                                                                                                                                                                                                            |
> | -------------------------- | :------------------------------: | -------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
> | `contract_address`         |                0                 | `FieldElement`       | The address of the contract invoked by this transaction.                                                                                                                                                                                                                                                                                               |
> ```

I think that we should remove this. In the feeder gateway we use "contract_address" all around (currently also in what's planned for 0.10.0). Also, the notion of account exists since we added fees, so even v0 transactions have accounts (only very old transactions, before versioning, have a contract_address which isn't an account).



_Code quote:_
```Markdown
contract_address
```
___
*[`docs/Blocks/transactions.md` line 65 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-6vzr9uWmW-PLDcuq:-NA-6vzr9uWmW-PLDcur:b-pokojt) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/447fd62513b83e21eaec598ac735d48c25b4fc10/docs/Blocks/transactions.md#L65)):*
> ```Markdown
> | `signature`                |               0,1                | `List<FieldElement>` | Additional information given by the sender, used to validate the transaction.                                                                                                                                                                                                                                                              |
> | `max_fee`                  |               0,1                | `FieldElement`       | The maximum fee that the sender is willing to pay for the transaction                                                                                                                                                                                                                                                                                  |
> | `nonce`                    |               0,1                | `FieldElement`       | (Transaction version 1)<br/>The transaction nonce.                                                                                                                                                                                                                                                                                                     |
> ```

the nonce is only a part of v1 transaction



_Code quote:_
```Markdown
nonce
```
___
*[`docs/Blocks/transactions.md` line 80 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-9C-e3Q4_pw3nQeQM:-NA-9C-f5Ystw6Sx4A8q:bq54rgd) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/447fd62513b83e21eaec598ac735d48c25b4fc10/docs/Blocks/transactions.md#L80)):*
> ```Markdown
> :::
> 
> ### Calculating the hash of an invoke transaction
> ```

We need to have some separation here for invoke v=0 and v=1, the below computation only represents v0. The hash of v1 isn't fully determined (see starknet-eng-product), so I'm marking here.
___
*[`docs/Blocks/transactions.md` line 115 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-9hkKBzJb3Reir7Za:-NA-9hkKBzJb3Reir7Zb:b3yzsv1) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/447fd62513b83e21eaec598ac735d48c25b4fc10/docs/Blocks/transactions.md#L115)):*
> ```Markdown
> </APITable>
> 
> ### Calculating the hash of a declare transaction
> ```

the hash of declare transaction changes: 
- class_hash moves instead of the second zero (which used to be a placeholder for calldata
- the last hashed argument is the nonce (after chain_id)
___
*[`docs/Blocks/transactions.md` line 121 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-9gOp5Zo75wm0N1Ih:-NA-9gOp5Zo75wm0N1Ii:b-9zhyd7) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/447fd62513b83e21eaec598ac735d48c25b4fc10/docs/Blocks/transactions.md#L121)):*
> ```Markdown
> $$
> \begin{aligned}
> \text{invoke\_tx\_hash} = h( & \text{"declare"}, \text{version}, \text{sender\_address}, \\& 0, 0, \text{max\_fee}, \text{chain\_id}, \text{class\_hash})
> ```

declare



_Code quote:_
```Markdown
invoke
```


<!-- Sent from Reviewable.io -->

2022-08-21 13:46 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: all files reviewed, 12 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`docs/Blocks/transactions.md` line 60 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jbIMD-5sGB4qFJZXF:-NA-U3DT2DxyhfU7rBe_:b-i5cb3n) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L60)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Agreed, but we should move to this terminology in the feeder gateway as well
</blockquote></details>

I changed this to `sender_address`.
___
*[`docs/Blocks/transactions.md` line 62 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jam4N9xE6x-MNmsAM:-NA-V8Yc0M4GK5Lb4If8:bbeh9ms) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L62)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

This is actually differnet in each version.
In version 0 it is the args that are passed to the invoked unction.
In version 1 it is the args that are passed to `validate` and to `execute`

Maybe we should consider having to different tables.
</blockquote></details>

PTAL now.
___
*[`docs/Blocks/transactions.md` line 65 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jaT9oCSP9-Ng25EIE:-NA-Vnpe5p42I-9wLX9v:bzhbg) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L65)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

We should add here a link to the place that describes what a nonce is. We shouldn't assume it is a common knowledge.
</blockquote></details>

Where is that? I don't see anything explaining what a nonce is in the StarkNet docs.
___
*[`docs/Blocks/transactions.md` line 70 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9j_mvD5ZqXo0W1SikE:-NA-_CMTA9a14ClSl-aN:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L70)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

We should change this section to explain the fact that we are now moving to tx version 1 and tx version 0 will be deprecated in v0.11

Please also add a todo to change this section in v0.11 when we deprecate tranaction version 0.
</blockquote></details>

Done.
___
*[`docs/Blocks/transactions.md` line 76 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9ja0pj1lSIwppeLRpx:-NA-aRpC8gFE7lACjBMc:bceiltg) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L76)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Please clarify here that the version should be different from the version specified in the table, or specifically from 0 or 1.
</blockquote></details>

I don't understand this. First of all, this says that testnet is production. That sounds wrong to me.

Secondly, how do you use a different transaction for testing purposes when the OS doesn't allow it?
___
*[`docs/Blocks/transactions.md` line 109 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jbXiiEoebMb9YMNCP:-NA-bAgU0k5Hn0d9vOdk:bb6un1j) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L109)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

same change as above
</blockquote></details>

Done
___
*[`docs/Blocks/transactions.md` line 49 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-AUlO-E4WzdMk8BX4:-NA-Gs5L1XgGs4YNOiRR:bviadkz) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/447fd62513b83e21eaec598ac735d48c25b4fc10/docs/Blocks/transactions.md#L49)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

we need to add a warning/info that invoke v0 will be deprecated in future StarkNet versions
</blockquote></details>

I think we need to add a page listing deprecated and removed features.
___
*[`docs/Blocks/transactions.md` line 59 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-7fIb8gaIbYkrTvxl:-NA-SuL_7kHCQnxVOQZ1:bncphru) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/447fd62513b83e21eaec598ac735d48c25b4fc10/docs/Blocks/transactions.md#L59)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think that we should remove this. In the feeder gateway we use "contract_address" all around (currently also in what's planned for 0.10.0). Also, the notion of account exists since we added fees, so even v0 transactions have accounts (only very old transactions, before versioning, have a contract_address which isn't an account).
</blockquote></details>

@bbrandtom I don't understand: Are you saying that we should remove this parameter (`contract_address`) from the documentation or is this a comment for @arielelp that it should be removed from the spec?

Your comment about the syntax of contract_address--are you saying that the correct syntax is the word `contract_` following by an address?
___
*[`docs/Blocks/transactions.md` line 65 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-6vzr9uWmW-PLDcuq:-NA-Vyj-DMlq_n8dbztJ:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/447fd62513b83e21eaec598ac735d48c25b4fc10/docs/Blocks/transactions.md#L65)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

the nonce is only a part of v1 transaction
</blockquote></details>

Done.
___
*[`docs/Blocks/transactions.md` line 80 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-9C-e3Q4_pw3nQeQM:-NA-amyo8IX6Q9Pioqar:bfudfea) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/447fd62513b83e21eaec598ac735d48c25b4fc10/docs/Blocks/transactions.md#L80)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

We need to have some separation here for invoke v=0 and v=1, the below computation only represents v0. The hash of v1 isn't fully determined (see starknet-eng-product), so I'm marking here.
</blockquote></details>

I can't do anything here until I have the full info. I'm leaving as-is for now.
___
*[`docs/Blocks/transactions.md` line 115 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-9hkKBzJb3Reir7Za:-NA-dmFB9kmtMuy2Yhgx:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/447fd62513b83e21eaec598ac735d48c25b4fc10/docs/Blocks/transactions.md#L115)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

the hash of declare transaction changes: 
- class_hash moves instead of the second zero (which used to be a placeholder for calldata
- the last hashed argument is the nonce (after chain_id)
</blockquote></details>

Done.
___
*[`docs/Blocks/transactions.md` line 121 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-9gOp5Zo75wm0N1Ih:-NA-dMF_7_TK_EpgZ2MK:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/447fd62513b83e21eaec598ac735d48c25b4fc10/docs/Blocks/transactions.md#L121)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

declare
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-21 13:50 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: all files reviewed, 12 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`docs/Blocks/transactions.md` line 62 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jam4N9xE6x-MNmsAM:-NA-eN5zDm3h9V1EImys:b-dalru) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L62)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

PTAL now.
</blockquote></details>

I labeled the definition per tx version. 
___
*[`docs/Blocks/transactions.md` line 65 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jaT9oCSP9-Ng25EIE:-NA-eDEc5pBOYygiSIdt:b-rvm6px) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L65)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Where is that? I don't see anything explaining what a nonce is in the StarkNet docs.
</blockquote></details>

Oh, creating this topic is the 4th doc task for 0.10. Not done yet. Once the page exists I can add a link here.
___
*[`docs/Blocks/transactions.md` line 49 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-AUlO-E4WzdMk8BX4:-NA-eegVBsgqvBjoTiLB:b-scvjan) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/447fd62513b83e21eaec598ac735d48c25b4fc10/docs/Blocks/transactions.md#L49)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

I think we need to add a page listing deprecated and removed features.
</blockquote></details>

I added a note saying that tx 0 is deprecated and will be unsupported.


<!-- Sent from Reviewable.io -->

2022-08-21 14:32 UTC, ArielElp requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)

___
*[`docs/Blocks/transactions.md` line 62 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jam4N9xE6x-MNmsAM:-NA-k3vj0z54a-vobIXx:b-9n4gzs) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L62)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

I labeled the definition per tx version. 
</blockquote></details>

I think that it's better to separate (as is, you can keep the current structure just without the supported in version column)

My suggestion: under invoke transaction have subscetions for invoke v0, invoke v1, where each has another subsection for the hash computation. Will be much easier to go through.
___
*[`docs/Blocks/transactions.md` line 76 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9ja0pj1lSIwppeLRpx:-NA-nozh0bEYkFI8SCLg:b35py92) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L76)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

I don't understand this. First of all, this says that testnet is production. That sounds wrong to me.

Secondly, how do you use a different transaction for testing purposes when the OS doesn't allow it?
</blockquote></details>

Maybe we need a better word for "testnet or mainnet". The OS is only used for proving, proving happens on testnet/mainnet. If I'm simulating StarkNet on my own computer, I don't care about the OS. Obviously I'm expecting transactions to run in the same way as they would on the real StarkNet, but versions are a useful example in which the user may want a different behavior, for otherwise a leaked signed transaction that I used for testing purposes may be submitted to the real StarkNet.
___
*[`docs/Blocks/transactions.md` line 59 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-7fIb8gaIbYkrTvxl:-NA-iTjl24bZQrjrJbg0:b-yihelo) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/447fd62513b83e21eaec598ac735d48c25b4fc10/docs/Blocks/transactions.md#L59)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

@bbrandtom I don't understand: Are you saying that we should remove this parameter (`contract_address`) from the documentation or is this a comment for @arielelp that it should be removed from the spec?

Your comment about the syntax of contract_address--are you saying that the correct syntax is the word `contract_` following by an address?
</blockquote></details>

It's Ariel

I'm unblocking, if we're gonna rename this to sender_address for v1 txs on our end then it makes sense to have this separation here
___
*[`docs/Blocks/transactions.md` line 54 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-kXj8DZ6DMbbmx2y3:-NA-kXj8DZ6DMbbmx2y4:bpyjy6m) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/2e29161092d28c2cc8f3fc0ace8faafa15a3d7fe/docs/Blocks/transactions.md#L54)):*
> ```Markdown
> 
> :::info
> Each version of the StarkNet OS contains a hard-coded version of each transaction, and can only accept transactions
> ```

This comment is problematic. If you have two different sections for v0/v1 then you can just have a warning that it's deprecated under the v0 section. 
___
*[`docs/Blocks/transactions.md` line 54 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-lEXY0q06JR86jxKf:-NA-lEXY0q06JR86jxKg:b6c7ejr) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/2e29161092d28c2cc8f3fc0ace8faafa15a3d7fe/docs/Blocks/transactions.md#L54)):*
> ```Markdown
> 
> :::info
> Each version of the StarkNet OS contains a hard-coded version of each transaction, and can only accept transactions
> ```

There is only one StarkNet OS in place. Think about it as the final judge on what txs are legal in StarkNet. The OS is only used for proving, so if you don't really care about proving (e.g. are using the starknet devnet) - the OS doesn't necessarily limit you.



_Code quote:_
```Markdown
Each version of the StarkNet OS
```
___
*[`docs/Blocks/transactions.md` line 57 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-mxQxDbfW_yMU9DdK:-NA-mxQxDbfW_yMU9DdL:b-ms5src) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/2e29161092d28c2cc8f3fc0ace8faafa15a3d7fe/docs/Blocks/transactions.md#L57)):*
> ```Markdown
> with this version. A transaction with a different version cannot be included in a proof, which protects the user.
> 
> You can use a different transaction version for testing purposes, because even if the transaction is properly signed, it can never be included in the production StarkNet (testnet or mainnet).
> ```

You can extract this to a tip titled "transaction query version"

Consider adding in the end:
Different tools, such as StarkNet devnet (github link) or the testing framework (cairo-docs link) , will allow you to submit a transaction with version v+2**128, where v is a supported transaction version in the production StarkNet.



_Code quote:_
```Markdown
You can use a different transaction version for testing purposes, because even if the transaction is properly signed, it can never be included in the production StarkNet (testnet or mainnet).
```


<!-- Sent from Reviewable.io -->

2022-08-22 07:07 UTC, bbrandtom requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: all files reviewed, 8 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)

___
*[`docs/Blocks/transactions.md` line 62 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jam4N9xE6x-MNmsAM:-NA3M8trEPbyesW5LG2c:bj83o30) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L62)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I think that it's better to separate (as is, you can keep the current structure just without the supported in version column)

My suggestion: under invoke transaction have subscetions for invoke v0, invoke v1, where each has another subsection for the hash computation. Will be much easier to go through.
</blockquote></details>

I agree with Ariel, this is very conufsing now. We might even want to explain in high level the flow of each transactions ,which is really different.
___
*[`docs/Blocks/transactions.md` line 65 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jaT9oCSP9-Ng25EIE:-NA3MJ9t1UmCQS6z3Xp3:b-crcspn) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L65)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Oh, creating this topic is the 4th doc task for 0.10. Not done yet. Once the page exists I can add a link here.
</blockquote></details>

Ok, please add a TODO
___
*[`docs/Blocks/transactions.md` line 10 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA3LM7M9ip2AyPENpoK:-NA3LM7M9ip2AyPENpoL:b-qtt0nx) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/2e29161092d28c2cc8f3fc0ace8faafa15a3d7fe/docs/Blocks/transactions.md#L10)):*
> ```Markdown
> 
> :::important
> The deploy transaction is deprecated and will be removed in a future release of StarkNet OS. To deploy new contract instances, you can use the `deploy` syscall. For more information, see [contract classes](../Contracts/contract-classes.md).
> ```

It's a future release of StarkNet, not only the StarkNet OS (which is only a part of the whole system)
Also please add a TODO to remove this on v0.11
___
*[`docs/Blocks/transactions.md` line 61 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA3LxK05BU-UR_YiOfq:-NA3LxK05BU-UR_YiOfr:bta6x1j) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/2e29161092d28c2cc8f3fc0ace8faafa15a3d7fe/docs/Blocks/transactions.md#L61)):*
> ```Markdown
> 
> :::important
> Transaction version 0 is deprecated and will be removed in a future release of StarkNet OS.
> ```

It's a future release of StarkNet, not only the StarkNet OS (which is only a part of the whole system).

Also please add a TODO to remove this on v0.11


<!-- Sent from Reviewable.io -->

2022-08-22 15:10 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: all files reviewed, 8 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`docs/Blocks/transactions.md` line 62 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jam4N9xE6x-MNmsAM:-NA4aQ-7EvnI-yfcp6Vx:b-n9d15f) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L62)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

I agree with Ariel, this is very conufsing now. We might even want to explain in high level the flow of each transactions ,which is really different.
</blockquote></details>

What would do you envision as the content of the sections entitled invoke v0, invoke v1? Just the tables?
___
*[`docs/Blocks/transactions.md` line 65 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jaT9oCSP9-Ng25EIE:-NA55O0h198Rs3lIcY9I:bg8eukm) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L65)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Ok, please add a TODO
</blockquote></details>

Done. Added a not in Monday
___
*[`docs/Blocks/transactions.md` line 76 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9ja0pj1lSIwppeLRpx:-NA55aTIEg8UmLa1HFpk:b2nhysk) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L76)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Maybe we need a better word for "testnet or mainnet". The OS is only used for proving, proving happens on testnet/mainnet. If I'm simulating StarkNet on my own computer, I don't care about the OS. Obviously I'm expecting transactions to run in the same way as they would on the real StarkNet, but versions are a useful example in which the user may want a different behavior, for otherwise a leaked signed transaction that I used for testing purposes may be submitted to the real StarkNet.
</blockquote></details>

ack
___
*[`docs/Blocks/transactions.md` line 10 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA3LM7M9ip2AyPENpoK:-NA4OmjSEb7ophJ1JM_5:b-2u5liv) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/2e29161092d28c2cc8f3fc0ace8faafa15a3d7fe/docs/Blocks/transactions.md#L10)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

It's a future release of StarkNet, not only the StarkNet OS (which is only a part of the whole system)
Also please add a TODO to remove this on v0.11
</blockquote></details>

Done. See Monday item https://starkware.monday.com/boards/2575505837/pulses/3118603594.
___
*[`docs/Blocks/transactions.md` line 54 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-kXj8DZ6DMbbmx2y3:-NA4Q9NR1dFe4JFy_Mh8:b-am14nv) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/2e29161092d28c2cc8f3fc0ace8faafa15a3d7fe/docs/Blocks/transactions.md#L54)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

This comment is problematic. If you have two different sections for v0/v1 then you can just have a warning that it's deprecated under the v0 section. 
</blockquote></details>

Done. I removed this *info* section, and for in the parameter tables, I added a deprecation message for v0.
___
*[`docs/Blocks/transactions.md` line 54 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-lEXY0q06JR86jxKf:-NA4Rdx996oePhI5LPXY:b-hkrzwf) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/2e29161092d28c2cc8f3fc0ace8faafa15a3d7fe/docs/Blocks/transactions.md#L54)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

There is only one StarkNet OS in place. Think about it as the final judge on what txs are legal in StarkNet. The OS is only used for proving, so if you don't really care about proving (e.g. are using the starknet devnet) - the OS doesn't necessarily limit you.
</blockquote></details>

Done. Changed all occurrences of "the StarkNet OS" to "StarkNet".
___
*[`docs/Blocks/transactions.md` line 57 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-mxQxDbfW_yMU9DdK:-NA4RpQ6DbzQAzy-g9rz:b-m0d2hp) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/2e29161092d28c2cc8f3fc0ace8faafa15a3d7fe/docs/Blocks/transactions.md#L57)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

You can extract this to a tip titled "transaction query version"

Consider adding in the end:
Different tools, such as StarkNet devnet (github link) or the testing framework (cairo-docs link) , will allow you to submit a transaction with version v+2**128, where v is a supported transaction version in the production StarkNet.
</blockquote></details>

Done. It's not common practice to add a title to admonitions (tip/note/caution etc.). I'll change this to:
```
:::tip
Each version of StarkNet contains a hard-coded version of each transaction, and can only accept transactions
with this version. A transaction with a different version cannot be included in a proof, which protects the user.

You can use various testing tools to submit a transaction with any supported transaction version in the StarkNet production environment. These tools include [StarkNet devnet](https://github.com/Shard-Labs/starknet-devnet) or the testing framework. For more information on the testing framework, see [Hello Cairo](https://www.cairo-lang.org/docs/index.html).
:::
```
If it deserves a title, it's generally not an admonition. It's a section of its own.
___
*[`docs/Blocks/transactions.md` line 61 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA3LxK05BU-UR_YiOfq:-NA4VLvi8w4jigjj66Kx:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/2e29161092d28c2cc8f3fc0ace8faafa15a3d7fe/docs/Blocks/transactions.md#L61)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

It's a future release of StarkNet, not only the StarkNet OS (which is only a part of the whole system).

Also please add a TODO to remove this on v0.11
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-23 10:07 UTC, ArielElp requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: 0 of 1 files reviewed, 14 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)

___
*[`docs/Blocks/transactions.md` line 62 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-N9jam4N9xE6x-MNmsAM:-NA92Rk99UdYklaomFsV:b-fdri48) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/10aa796a952027c1d2909f7b6977ee9795e352ee/docs/Blocks/transactions.md#L62)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

What would do you envision as the content of the sections entitled invoke v0, invoke v1? Just the tables?
</blockquote></details>

There will also be a description of the flow, which I'll add
___
*[`docs/Blocks/transactions.md` line 57 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-mxQxDbfW_yMU9DdK:-NA98b9H8555LC7PEdg8:bga56m4) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/2e29161092d28c2cc8f3fc0ace8faafa15a3d7fe/docs/Blocks/transactions.md#L57)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Done. It's not common practice to add a title to admonitions (tip/note/caution etc.). I'll change this to:
```
:::tip
Each version of StarkNet contains a hard-coded version of each transaction, and can only accept transactions
with this version. A transaction with a different version cannot be included in a proof, which protects the user.

You can use various testing tools to submit a transaction with any supported transaction version in the StarkNet production environment. These tools include [StarkNet devnet](https://github.com/Shard-Labs/starknet-devnet) or the testing framework. For more information on the testing framework, see [Hello Cairo](https://www.cairo-lang.org/docs/index.html).
:::
```
If it deserves a title, it's generally not an admonition. It's a section of its own.
</blockquote></details>

The point is that you can use UNSUPPORTED versions in different toolings. The fear is that if you sign a transaction for devnet, someone will use it in the real StarkNet (as it's properly signed and everything). I prefer the sentence that we currently have in the docs:

"Note that setting a different version can be useful for testing purposes, since even if the transaction is properly signed, it can never be included in StarkNet (testnet or mainnet)." - I don't want to commit to toolings here.



_Code quote:_
```Markdown
You can use various testing tools to submit a transaction with any supported transaction version in the StarkNet production environment. These tools include [StarkNet devnet](https://github.com/Shard-Labs/starknet-devnet) or the testing framework. For more information on the testing framework, see [Hello Cairo](https://www.cairo-lang.org/docs/index.html).
```
___
*[`docs/Blocks/transactions.md` line 1 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA93U088ypica1q01iX:-NA93U088ypica1q01iY:b-l6mwxj) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L1)):*
> ```Markdown
> `INVOKE_FUNCTION`import APITable from '@site/src/components/APITable';
> ```

remove



_Code quote:_
```Markdown
`INVOKE_FUNCTION`
```
___
*[`docs/Blocks/transactions.md` line 51 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA95DCd9xQCatcMepOj:-NA95DCd9xQCatcMepOk:bbnsiw2) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L51)):*
> ```Markdown
> ## `INVOKE_FUNCTION` Transaction
> 
> The `INVOKE_FUNCTION` transaction is the main transaction type used to invoke contract functions in StarkNet.
> ```

Let's revert this change, INVOKE_FUNCTION is an internal name

I understand that Invoke transaction may be a bad name as it can be taken as an action, but I don't have a better name currently.

@bbrandtom WDYT 



_Code quote:_
```Markdown
## `INVOKE_FUNCTION` Transaction

The `INVOKE_FUNCTION` transaction is the main transaction type used to invoke contract functions in StarkNet.
```
___
*[`docs/Blocks/transactions.md` line 54 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA9746vAmwUoQWbQjx2:-NA9746vAmwUoQWbQjx3:b-rcuugv) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L54)):*
> ```Markdown
> 
> :::tip
> Each version of StarkNet contains a hard-coded version of each transaction, and can only accept transactions
> ```

transaction type



_Code quote:_
```Markdown
transaction
```
___
*[`docs/Blocks/transactions.md` line 54 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA98Ams9K0JKnUZOSV_:-NA98Ams9K0JKnUZOSVa:b-6hvvk7) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L54)):*
> ```Markdown
> 
> :::tip
> Each version of StarkNet contains a hard-coded version of each transaction, and can only accept transactions
> ```

list of supported versions



_Code quote:_
```Markdown
version
```
___
*[`docs/Blocks/transactions.md` line 55 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA97BBw2KgbsU-J_CLO:-NA97BBw2KgbsU-J_CLP:b-u1wkln) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L55)):*
> ```Markdown
> :::tip
> Each version of StarkNet contains a hard-coded version of each transaction, and can only accept transactions
> with this version. A transaction with a different version cannot be included in a proof, which protects the user.
> ```

how? let's remove this entirely

A transaction with a different version cannot be included in a proof, and thus will never be added to a StarkNet block.



_Code quote:_
```Markdown
which protects the user
```
___
*[`docs/Blocks/transactions.md` line 66 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA92GT53fCWBH5quAf2:-NA92GT53fCWBH5quAf3:b-njhaan) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L66)):*
> ```Markdown
> An `INVOKE_FUNCTION` transaction has the following fields:
> 
> **Invoke transaction version 1**
> ```

let's have a subtitles here, ###
___
*[`docs/Blocks/transactions.md` line 73 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA94j_D6tIjAMVKMLmn:-NA94j_D6tIjAMVKMLmo:b-hio373) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L73)):*
> ```Markdown
> | ---------------------- | -------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
> | `sender_address`       | `FieldElement`       | The address of the sender of this transaction.                                                                                                                                                                          |
> | `entry_point_selector` | `FieldElement`       | The encoding of the selector for the function invoked (the entry point in the contract)                                                                                                                                 |
> ```

remove row, there is no selector in v1



_Code quote:_
```Markdown
entry_point_selector
```
___
*[`docs/Blocks/transactions.md` line 82 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA92n [...]

2022-08-24 11:59 UTC, bbrandtom submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: all files reviewed, 10 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`docs/Blocks/transactions.md` line 10 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA3LM7M9ip2AyPENpoK:-NAEhPKz8XiRQG45vtUN:bpvk2wt) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/2e29161092d28c2cc8f3fc0ace8faafa15a3d7fe/docs/Blocks/transactions.md#L10)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Done. See Monday item https://starkware.monday.com/boards/2575505837/pulses/3118603594.
</blockquote></details>

I prefer we add it here. But we can do it next time.
___
*[`docs/Blocks/transactions.md` line 51 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA95DCd9xQCatcMepOj:-NAEhYoU5fvk1e1wFjGU:b-6qq481) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L51)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Let's revert this change, INVOKE_FUNCTION is an internal name

I understand that Invoke transaction may be a bad name as it can be taken as an action, but I don't have a better name currently.

@bbrandtom WDYT 
</blockquote></details>

Let's just call it invoke transaction


<!-- Sent from Reviewable.io -->

2022-08-24 13:08 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: all files reviewed, 10 unresolved discussions (waiting on @ArielElp)

___
*[`docs/Blocks/transactions.md` line 59 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-7fIb8gaIbYkrTvxl:-NA4VXEG3-jbM6zZMl6t:b-heos5d) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/447fd62513b83e21eaec598ac735d48c25b4fc10/docs/Blocks/transactions.md#L59)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

It's Ariel

I'm unblocking, if we're gonna rename this to sender_address for v1 txs on our end then it makes sense to have this separation here

</blockquote></details>

@bbrandtom I still don't understand what you're asking me to do here.
___
*[`docs/Blocks/transactions.md` line 10 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA3LM7M9ip2AyPENpoK:-NAEilye1FodXsjmv1eL:b-g1rnr7) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/2e29161092d28c2cc8f3fc0ace8faafa15a3d7fe/docs/Blocks/transactions.md#L10)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

I prefer we add it here. But we can do it next time.
</blockquote></details>

I don't understand what you mean. How do we add here a TODO to remove something in a future release?
___
*[`docs/Blocks/transactions.md` line 57 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-mxQxDbfW_yMU9DdK:-NAEweyl0Q6MnaoasUDT:br5ln4) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/2e29161092d28c2cc8f3fc0ace8faafa15a3d7fe/docs/Blocks/transactions.md#L57)):*
> "Note that setting a different version can be useful for testing purposes, since even if the transaction is properly signed, it can never be included in StarkNet (testnet or mainnet)." - I don't want to commit to toolings here.
___
*[`docs/Blocks/transactions.md` line 1 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA93U088ypica1q01iX:-NAEpTip74i267aEurI8:b-a37zd0) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L1)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

remove
</blockquote></details>

It's not clear what an invoke or declare or deploy transaction is, even after I've scanned through Hello StarkNet and Hello Cairo, if an "invoke|deploy|declare transaction" refers to types of transaction, where the actual code syntax for defining/calling each transaction might be e.g. `put`, `call` or something else. I see that there are CLI commands `starknet invoke` and `starknet deploy`. But commands are not transactions. I see an example of running `starknet get_transaction` that returns details for a transaction including it's type, which is `INVOKE_FUNCTION`.

So where can I find info the clarify this? It must be explained somewhere.

In the meantime, I'm changing all occurrences of "invoke", "deploy" and "declare" in this topic to be a normal word, without any formatting or special case.
___
*[`docs/Blocks/transactions.md` line 54 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA9746vAmwUoQWbQjx2:-NAErk3p2JRwBx7uft9D:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L54)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

transaction type
</blockquote></details>

Done.
___
*[`docs/Blocks/transactions.md` line 54 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA98Ams9K0JKnUZOSV_:-NAErt1T7Zy4w0clMbzF:b80flwh) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L54)):*
I don't understand what you mean. This is the sentence that results from your suggestion:

> Each list of supported versions of StarkNet contains a hard-coded version of each transaction type, and can only accept transactions
with this version.

I don't understand this sentence.
___
*[`docs/Blocks/transactions.md` line 55 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA97BBw2KgbsU-J_CLO:-NAEsE4R6bhRXXbdrHan:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L55)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

how? let's remove this entirely

A transaction with a different version cannot be included in a proof, and thus will never be added to a StarkNet block.
</blockquote></details>

Done.
___
*[`docs/Blocks/transactions.md` line 66 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA92GT53fCWBH5quAf2:-NAEvsjJ8x0pcgPGoNTl:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L66)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

let's have a subtitles here, ###
</blockquote></details>

Done.
___
*[`docs/Blocks/transactions.md` line 73 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA94j_D6tIjAMVKMLmn:-NAEtssTDInCNNEMvOTW:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L73)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

remove row, there is no selector in v1
</blockquote></details>

Done.
___
*[`docs/Blocks/transactions.md` line 82 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA92nJF9wpUvh8ZtCqq:-NAEtxOn2s6gB_Aexp-T:byx1raq) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L82)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

let's have a subtitles here, ###
</blockquote></details>

I added the headings, but a table caption is not a heading, so I left the captions as bold text (will convert to real captions in AsciiDoc).


<!-- Sent from Reviewable.io -->

2022-08-24 13:10 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: all files reviewed, 10 unresolved discussions (waiting on @ArielElp)

___
*[`docs/Blocks/transactions.md` line 51 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA95DCd9xQCatcMepOj:-NAEy3Q58FPDNPBdJp1T:b-dvj2p4) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L51)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Let's just call it invoke transaction
</blockquote></details>

Either we need to come up with something clearer, or I need to understand better what an invoke transaction actually is. I have no idea what it is after reading this topic, and after scanning through Hello Cairo and Hello StarkNet.


<!-- Sent from Reviewable.io -->

2022-08-25 05:50 UTC, ArielElp submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)

___
*[`docs/Blocks/transactions.md` line 57 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-mxQxDbfW_yMU9DdK:-NAIY7QpD_9VsAxHbGjQ:b-t0nvpn) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/2e29161092d28c2cc8f3fc0ace8faafa15a3d7fe/docs/Blocks/transactions.md#L57)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

> "Note that setting a different version can be useful for testing purposes, since even if the transaction is properly signed, it can never be included in StarkNet (testnet or mainnet)." - I don't want to commit to toolings here.
</blockquote></details>

I guess you wanted to add something after the quote?
___
*[`docs/Blocks/transactions.md` line 54 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA98Ams9K0JKnUZOSV_:-NAIXeWSDzSKoKvmP4k6:b5gwyns) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L54)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

I don't understand what you mean. This is the sentence that results from your suggestion:

> Each list of supported versions of StarkNet contains a hard-coded version of each transaction type, and can only accept transactions
with this version.

I don't understand this sentence.
</blockquote></details>

Each version of StarkNet contains a hard-coded list of supported transaction versions for each transaction type, and can only accept transactions with a supported version. A transaction with a different version cannot be included in a proof. 
___
*[`docs/Blocks/transactions.md` line 55 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA97BBw2KgbsU-J_CLO:-NAIXVia8gnUHo2bgEdM:b5nlz31) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L55)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant removing only the "protects the user"


<!-- Sent from Reviewable.io -->

2022-08-25 09:35 UTC, bbrandtom requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: all files reviewed, 11 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`docs/Blocks/transactions.md` line 5 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NAJJgWe5oJIJHVzv6gk:-NAJJgWe5oJIJHVzv6gl:bqf9fsd) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/0678c80bbc44d500fb2f2adc27ba3a66a78a2e08/docs/Blocks/transactions.md#L5)):*
> ```Markdown
> # Transaction structure
> 
> StarkNet, in its Alpha version, supports two types of transactions: a _deploy_ transaction and an _invoke_ transaction. This topic describes the available fields for both of these transaction types and how the transaction hash is calculated in both cases.
> ```

we also support declare



_Code quote:_
```Markdown
 a _deploy_ transaction and an _invoke_ transaction.
```
___
*[`docs/Blocks/transactions.md` line 5 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NAJJvEA9n9Kp3G5i7TR:-NAJJvEA9n9Kp3G5i7TS:b-yliksb) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/0678c80bbc44d500fb2f2adc27ba3a66a78a2e08/docs/Blocks/transactions.md#L5)):*
> ```Markdown
> # Transaction structure
> 
> StarkNet, in its Alpha version, supports two types of transactions: a _deploy_ transaction and an _invoke_ transaction. This topic describes the available fields for both of these transaction types and how the transaction hash is calculated in both cases.
> ```

it's not related to Alpha, as we might not support deploy in the next version, and it will still be alpha.



_Suggestion:_
```Markdown
in its current version
```
___
*[`docs/Blocks/transactions.md` line 9 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NAJK9Bz2lEaJcB7p8G0:-NAJK9Bz2lEaJcB7p8G1:undefined) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/0678c80bbc44d500fb2f2adc27ba3a66a78a2e08/docs/Blocks/transactions.md#L9)):*
> ```Markdown
> ## Transaction versioning
> 
> Each list of supported versions of StarkNet contains a hard-coded version of each transaction type, and can only accept transactions with this version. A transaction with a different version cannot be included in a proof.
> ```





_Suggestion:_
```Markdown
block
```
___
*[`docs/Blocks/transactions.md` line 9 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NAJKDCmEwkME9kZIrin:-NAJKDCmEwkME9kZIrio:b-wo8cca) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/0678c80bbc44d500fb2f2adc27ba3a66a78a2e08/docs/Blocks/transactions.md#L9)):*
> ```Markdown
> ## Transaction versioning
> 
> Each list of supported versions of StarkNet contains a hard-coded version of each transaction type, and can only accept transactions with this version. A transaction with a different version cannot be included in a proof.
> ```

Not sure exactly what it means.



_Code quote:_
```Markdown
Each list of supported versions of StarkNet
```
___
*[`docs/Blocks/transactions.md` line 11 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NAJKMYn1h_eu5NmUE_x:-NAJKMYn1h_eu5NmUE_y:brm01r3) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/0678c80bbc44d500fb2f2adc27ba3a66a78a2e08/docs/Blocks/transactions.md#L11)):*
> ```Markdown
> Each list of supported versions of StarkNet contains a hard-coded version of each transaction type, and can only accept transactions with this version. A transaction with a different version cannot be included in a proof.
> 
> Setting a different version can be useful for testing purposes, since even if the transaction is properly signed, it can never be included in StarkNet, neither in testnet or in Mainnet.
> ```

This comment is a bit out of context IMO.
What does it mean to set? Where do I set it? Is it for users? For devs?
I suggest removing it from here.
___
*[`docs/Blocks/transactions.md` line 13 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NAJKYgrD_3QyR4jDNpJ:-NAJKYgrD_3QyR4jDNpK:b-nnax7c) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/0678c80bbc44d500fb2f2adc27ba3a66a78a2e08/docs/Blocks/transactions.md#L13)):*
> ```Markdown
> Setting a different version can be useful for testing purposes, since even if the transaction is properly signed, it can never be included in StarkNet, neither in testnet or in Mainnet.
> 
> You can use various testing tools to submit a transaction with any supported transaction version in the StarkNet production environment. These tools include [StarkNet devnet](https://github.com/Shard-Labs/starknet-devnet) or the testing framework. For more information on the testing framework, see [Hello Cairo](https://www.cairo-lang.org/docs/index.html).
> ```

Hello Cairo does not explain on the testing framework.
This is the link to where it is explained - https://www.cairo-lang.org/docs/hello_starknet/unit_tests.html - but I suggest removing it until we merge it to the same doc
___
*[`docs/Blocks/transactions.md` line 13 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NAJKvZwEMX_RtoknnT8:-NAJKvZwEMX_RtoknnT9:b-j36qct) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/0678c80bbc44d500fb2f2adc27ba3a66a78a2e08/docs/Blocks/transactions.md#L13)):*
> ```Markdown
> Setting a different version can be useful for testing purposes, since even if the transaction is properly signed, it can never be included in StarkNet, neither in testnet or in Mainnet.
> 
> You can use various testing tools to submit a transaction with any supported transaction version in the StarkNet production environment. These tools include [StarkNet devnet](https://github.com/Shard-Labs/starknet-devnet) or the testing framework. For more information on the testing framework, see [Hello Cairo](https://www.cairo-lang.org/docs/index.html).
> ```

Are we sure this is true? Doesn't Devnet enforce the tx version as well?
@arielelp 


<!-- Sent from Reviewable.io -->

2022-08-25 10:56 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: all files reviewed, 11 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)

___
*[`docs/Blocks/transactions.md` line 59 at r3](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-7fIb8gaIbYkrTvxl:-NAJYxGf-iVYVLOuUjIS:b-rv0999) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/447fd62513b83e21eaec598ac735d48c25b4fc10/docs/Blocks/transactions.md#L59)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

@bbrandtom I still don't understand what you're asking me to do here.
</blockquote></details>

I think the request has been fulfilled. I changed to `sender_address`.
___
*[`docs/Blocks/transactions.md` line 57 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA-mxQxDbfW_yMU9DdK:-NAJbfPd6-CZVyZfgeHC:b-ecuxfd) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/2e29161092d28c2cc8f3fc0ace8faafa15a3d7fe/docs/Blocks/transactions.md#L57)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

I guess you wanted to add something after the quote?
</blockquote></details>

Yeah, I got lost as I was doing this. I need to sit together with one of you on this.
___
*[`docs/Blocks/transactions.md` line 54 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA98Ams9K0JKnUZOSV_:-NAJcZcT6GqaQ0wApR8o:bb6un1j) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L54)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Each version of StarkNet contains a hard-coded list of supported transaction versions for each transaction type, and can only accept transactions with a supported version. A transaction with a different version cannot be included in a proof. 
</blockquote></details>

Done
___
*[`docs/Blocks/transactions.md` line 55 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NA97BBw2KgbsU-J_CLO:-NAJcUf58FYwpLY7z5ew:b-1v5i2i) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/eb149c1b378adcad29d6d50684deebf75e8f5ae4/docs/Blocks/transactions.md#L55)):*
> and thus will never be added to a StarkNet block.
OK. Done.
___
*[`docs/Blocks/transactions.md` line 5 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NAJJvEA9n9Kp3G5i7TR:-NAJaaarCPWSBL75t8uw:b88l03o) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/0678c80bbc44d500fb2f2adc27ba3a66a78a2e08/docs/Blocks/transactions.md#L5)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

it's not related to Alpha, as we might not support deploy in the next version, and it will still be alpha.
</blockquote></details>

Then I'm just removing this. It doesn't add anything.


<!-- Sent from Reviewable.io -->

2022-08-25 11:01 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @stoobie)

___
*[`docs/Blocks/transactions.md` line 5 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NAJJgWe5oJIJHVzv6gk:-NAJdqfD0OqRChIsXQjm:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/0678c80bbc44d500fb2f2adc27ba3a66a78a2e08/docs/Blocks/transactions.md#L5)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

we also support declare
</blockquote></details>

Done.
___
*[`docs/Blocks/transactions.md` line 9 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NAJK9Bz2lEaJcB7p8G0:-NAJdvUdEYzjcOxUBx0j:b-ru36h9) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/0678c80bbc44d500fb2f2adc27ba3a66a78a2e08/docs/Blocks/transactions.md#L9)):*
> ```Markdown
> ## Transaction versioning
> 
> Each list of supported versions of StarkNet contains a hard-coded version of each transaction type, and can only accept transactions with this version. A transaction with a different version cannot be included in a proof.
> ```

I don't see what you're talking about. 
___
*[`docs/Blocks/transactions.md` line 9 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NAJKDCmEwkME9kZIrin:-NAJdzs_CuDqUo_2qcD0:b5e2ue5) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/0678c80bbc44d500fb2f2adc27ba3a66a78a2e08/docs/Blocks/transactions.md#L9)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Not sure exactly what it means.
</blockquote></details>

I also didn't. I think it's fixed now.
___
*[`docs/Blocks/transactions.md` line 11 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NAJKMYn1h_eu5NmUE_x:-NAJe7FJ0yqW5Tsucbyj:b3o7gjw) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/0678c80bbc44d500fb2f2adc27ba3a66a78a2e08/docs/Blocks/transactions.md#L11)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

This comment is a bit out of context IMO.
What does it mean to set? Where do I set it? Is it for users? For devs?
I suggest removing it from here.
</blockquote></details>

You didn't quote anything so I don't have any context for this comment.
___
*[`docs/Blocks/transactions.md` line 13 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NAJKYgrD_3QyR4jDNpJ:-NAJeC42EL7_gnVYCOpl:b3o7gjw) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/0678c80bbc44d500fb2f2adc27ba3a66a78a2e08/docs/Blocks/transactions.md#L13)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Hello Cairo does not explain on the testing framework.
This is the link to where it is explained - https://www.cairo-lang.org/docs/hello_starknet/unit_tests.html - but I suggest removing it until we merge it to the same doc
</blockquote></details>

You didn't quote anything so I don't have any context for this comment.


<!-- Sent from Reviewable.io -->

2022-08-25 12:00 UTC, ArielElp reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`docs/Blocks/transactions.md` line 13 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-NAJKvZwEMX_RtoknnT8:-NAJrvTR8NSIBrcdQNbh:budvohj) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/0678c80bbc44d500fb2f2adc27ba3a66a78a2e08/docs/Blocks/transactions.md#L13)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Are we sure this is true? Doesn't Devnet enforce the tx version as well?
@arielelp 
</blockquote></details>

They do (because our backend logic does) but let's avoid discussing it here altogether 


<!-- Sent from Reviewable.io -->

2022-08-25 13:00 UTC, bbrandtom submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-:-NAK4iMIB43o_oaPh73d:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stoobie)



<!-- Sent from Reviewable.io -->

2022-08-28 11:24 UTC, bbrandtom approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/53#-:-NAZBTaN-h-AAXs6cy8c:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stoobie)



<!-- Sent from Reviewable.io -->

2022-08-28 12:34 UTC, merged