doc: Added option reference for `starknet-compile`.
starknet-community-libs/starknet-docs pull request #83
Opened 2022-10-20 12:56 UTC by stoobie

### Description of the Changes

The StarkNet compiler will be updated soon for Cairo 1.0/regenesis, so in order not to spend much time on something that will be obsolete within 3-6 months, this task is essentially to add the command line help (`starknet-compile --help`) to the docs.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

2022-10-24 12:36 UTC, bbrandtom requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`components/StarkNet/modules/develop/nav.adoc` line 38 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83#-NF8D-iV4Uw22xZSIwgX:-NF8D-iV4Uw22xZSIwgY:b-7im0sg) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/b798b69c092d79995e86a091facb55259f0d2da3/components/StarkNet/modules/develop/nav.adoc#L38)):*
> ```AsciiDoc
> 
> ** xref:CLI/commands.adoc[StarkNet CLI reference]
> ** xref:CLI/starknet-compiler-options.adoc[StarkNet compiler reference]
> ```

Why is it in a different section? I think it should be part of the StarkNet CLI.
___
*[`components/StarkNet/modules/develop/pages/CLI/starknet-compiler-options.adoc` line 12 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83#-NF8EgEw0RoKBvOCm5IF:-NF8EgEw0RoKBvOCm5IG:byg5qiq) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/b798b69c092d79995e86a091facb55259f0d2da3/components/StarkNet/modules/develop/pages/CLI/starknet-compiler-options.adoc#L12)):*
> ```AsciiDoc
> 
> == Usage
> ```

I think an example will help a lot


<!-- Sent from Reviewable.io -->

2022-10-24 15:17 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/develop/nav.adoc` line 38 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83#-NF8D-iV4Uw22xZSIwgX:-NF9XfkbEfkrUnqDvk4t:b-rnyaz2) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/b798b69c092d79995e86a091facb55259f0d2da3/components/StarkNet/modules/develop/nav.adoc#L38)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Why is it in a different section? I think it should be part of the StarkNet CLI.
</blockquote></details>

If I understand correctly, the compiler lets you compiler Cairo code into something (a smart contract?) that you can execute on StarkNet. 

You would then interact with it using an API or the StarkNet CLI. Those are two separate things. 

The usage for the CLI is:

$ starknet <command> <options>

Whereas the usage for the compiler is:

$ starknet-compile <options>

They are separate commands, and each has its own CLI help.
___
*[`components/StarkNet/modules/develop/pages/CLI/starknet-compiler-options.adoc` line 12 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83#-NF8EgEw0RoKBvOCm5IF:-NF9YhM1ANSx07DRGVSn:bytoo8b) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/b798b69c092d79995e86a091facb55259f0d2da3/components/StarkNet/modules/develop/pages/CLI/starknet-compiler-options.adoc#L12)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

I think an example will help a lot
</blockquote></details>

I agree. 

In general there's a lot that could be improved here.  The idea here is to provide the minimal information because this help will be, as I understand from Ariel, outdated within 3 months at the regenesis. But I'm happy for me or for James to spend more time on this if you feel it's important. I just thought it was lower priority considering it's projected lifespan.


<!-- Sent from Reviewable.io -->

2022-10-26 07:25 UTC, dan-ziv commented
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-83/documentation/ .

2022-10-30 07:16 UTC, bbrandtom requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @stoobie)

___
*[`components/StarkNet/modules/develop/pages/CLI/starknet-compiler-options.adoc` line 12 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83#-NF8EgEw0RoKBvOCm5IF:-NF9w4mk8dknQqm_1m9Z:b21chdp) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/a3cb55b784bae0cc899dd22b137edcd95e313cd5/components/StarkNet/modules/develop/pages/CLI/starknet-compiler-options.adoc#L12)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

I agree. 

In general there's a lot that could be improved here.  The idea here is to provide the minimal information because this help will be, as I understand from Ariel, outdated within 3 months at the regenesis. But I'm happy for me or for James to spend more time on this if you feel it's important. I just thought it was lower priority considering it's projected lifespan.
</blockquote></details>

I agree it’s low priority but a simple example from Hello StarkNet is easy to add


<!-- Sent from Reviewable.io -->

2022-10-30 14:41 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/develop/pages/CLI/starknet-compiler-options.adoc` line 12 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83#-NF8EgEw0RoKBvOCm5IF:-NFcto6X0KPAlY9euY-2:b-vgv8os) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/a3cb55b784bae0cc899dd22b137edcd95e313cd5/components/StarkNet/modules/develop/pages/CLI/starknet-compiler-options.adoc#L12)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

I agree it’s low priority but a simple example from Hello StarkNet is easy to add
</blockquote></details>

Ok. No problem. PTAL now.


<!-- Sent from Reviewable.io -->

2022-10-30 14:41 UTC, dan-ziv commented
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-83/documentation/ .

2022-10-31 14:24 UTC, ArielElp requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @bbrandtom and @stoobie)

___
*[`components/StarkNet/modules/develop/pages/CLI/starknet-compiler-options.adoc` line 29 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83#-NFiQ36t1TzZZz1YTcxX:-NFiQ36t1TzZZz1YTcxY:b2niczw) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/a518cb5d7ad86ed16a34d278d221cae6aee4dc49/components/StarkNet/modules/develop/pages/CLI/starknet-compiler-options.adoc#L29)):*
> ```AsciiDoc
> The following example compiles the file `contract.cairo`. It generates two files:
> 
> contract_compiled.json:: The contract class. This file contains the bytecode and all other information necessary to execute a contract. For information on contract classes, see xref:Contracts/contract-classes.adoc[].
> ```

the



_Code quote:_
```AsciiDoc
a
```
___
*[`components/StarkNet/modules/develop/pages/CLI/starknet-compiler-options.adoc` line 31 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83#-NFiQ9r64vtHEAwbRuxP:-NFiQ9r64vtHEAwbRuxQ:bmnbvot) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/a518cb5d7ad86ed16a34d278d221cae6aee4dc49/components/StarkNet/modules/develop/pages/CLI/starknet-compiler-options.adoc#L31)):*
> ```AsciiDoc
> contract_compiled.json:: The contract class. This file contains the bytecode and all other information necessary to execute a contract. For information on contract classes, see xref:Contracts/contract-classes.adoc[].
> +
> Declare this contract class on StarkNet.*
> ```

Remove, compiling doesn't have to be coupled to anything that's going on in StarkNet (but you're right in the sense that if you want to declare, then you need the output of the compilation, so if we have starknet declare in the CLI we can link to there)



_Code quote:_
```AsciiDoc
Declare this contract class on StarkNet.*
```


<!-- Sent from Reviewable.io -->

2022-11-02 07:19 UTC, bbrandtom submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83#-:-NFrCTNaCL-9KiNClzEM:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @stoobie)



<!-- Sent from Reviewable.io -->

2022-11-02 13:06 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp)

___
*[`components/StarkNet/modules/develop/pages/CLI/starknet-compiler-options.adoc` line 31 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83#-NFiQ9r64vtHEAwbRuxP:-NFsRlMkAiwsMH9LBptM:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/a518cb5d7ad86ed16a34d278d221cae6aee4dc49/components/StarkNet/modules/develop/pages/CLI/starknet-compiler-options.adoc#L31)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Remove, compiling doesn't have to be coupled to anything that's going on in StarkNet (but you're right in the sense that if you want to declare, then you need the output of the compilation, so if we have starknet declare in the CLI we can link to there)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-02 13:08 UTC, dan-ziv commented
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-83/documentation/ .

2022-11-02 14:15 UTC, ArielElp approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/83#-:-NFsgR2nBO1j_trPkXvQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bbrandtom)



<!-- Sent from Reviewable.io -->

2022-11-02 14:45 UTC, dan-ziv commented
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-83/documentation/ .

2022-11-02 14:56 UTC, dan-ziv commented
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-83/documentation/ .

2022-11-02 15:09 UTC, merged