docs: Added operational info
starknet-community-libs/starknet-docs pull request #91
Opened 2022-10-25 15:13 UTC by stoobie

### Description of the Changes

Added StarkNet operational info.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

2022-10-25 19:39 UTC, LucasLvy requested changes
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/91)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp, @bbrandtom, and @stoobie)

___
*[`components/StarkNet/modules/ROOT/pages/Ecosystem/ref_operational_info.adoc` line 20 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/91#-NFFcwkY4OwHd5ugbzh0:-NFFcwkZ0UnID_ZAHqPr:bmqandr) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/a66d660d88fa43fbe35d07cd066543d6bd653a8d/components/StarkNet/modules/ROOT/pages/Ecosystem/ref_operational_info.adoc#L20)):*
> ```AsciiDoc
> == Bridged Tokens
> 
> The `starknet-addresses` repository contains the following `.json` files:
> ```

A table would be much better to display this information imo


<!-- Sent from Reviewable.io -->

2022-10-26 07:57 UTC, dan-ziv commented
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-91/documentation/ .

2022-10-26 08:22 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/91)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @ArielElp, @bbrandtom, and @LucasLvy)

___
*[`components/StarkNet/modules/ROOT/pages/Ecosystem/ref_operational_info.adoc` line 20 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/91#-NFFcwkY4OwHd5ugbzh0:-NFIIYks1PpntBOk0pIs:b-fzikkd) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/a66d660d88fa43fbe35d07cd066543d6bd653a8d/components/StarkNet/modules/ROOT/pages/Ecosystem/ref_operational_info.adoc#L20)):*
<details><summary><i>Previously, LucasLvy (Lucas) wrote…</i></summary><blockquote>

A table would be much better to display this information imo
</blockquote></details>

@lucaslvy Which info, the list of parameters?

Take a look at the preview to see how it appears: https://starknet-community-libs.github.io/starknet-docs/pr-91/documentation/Ecosystem/ref_operational_info/

Did you see my inline questions?


<!-- Sent from Reviewable.io -->

2022-10-26 08:22 UTC, dan-ziv commented
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-91/documentation/ .

2022-10-27 08:03 UTC, LucasLvy requested changes
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/91)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @ArielElp, @bbrandtom, and @stoobie)

___
*[`components/StarkNet/modules/ROOT/pages/Ecosystem/ref_operational_info.adoc` line 20 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/91#-NFFcwkY4OwHd5ugbzh0:-NFIhvIX76eJDS5pClWE:b-g1wpog) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/a66d660d88fa43fbe35d07cd066543d6bd653a8d/components/StarkNet/modules/ROOT/pages/Ecosystem/ref_operational_info.adoc#L20)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

@lucaslvy Which info, the list of parameters?

Take a look at the preview to see how it appears: https://starknet-community-libs.github.io/starknet-docs/pr-91/documentation/Ecosystem/ref_operational_info/

Did you see my inline questions?
</blockquote></details>

A table to display everything on this page and not link to the json file


<!-- Sent from Reviewable.io -->

2022-10-27 08:06 UTC, LucasLvy commented on components/StarkNet/modules/ROOT/pages/Ecosystem/ref_operational_info.adoc
> +// ??? This URL does not work. What is the correct URL???
Yes it's a base url for the api routes

2022-10-27 08:06 UTC, LucasLvy commented on components/StarkNet/modules/ROOT/pages/Ecosystem/ref_operational_info.adoc
> +// ??? This URL does not work. What is the correct URL???
Yes it's a base url for the api routes

2022-10-27 15:00 UTC, stoobie commented on components/StarkNet/modules/ROOT/pages/Ecosystem/ref_operational_info.adoc
> +// ??? This URL does not work. What is the correct URL???
PTAL

2022-10-30 07:02 UTC, bbrandtom approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 8 files at r9, 2 of 6 files at r10, 3 of 3 files at r11, 1 of 1 files at r12, 1 of 2 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/91#-:-NFbgeD12PuHRRaaXgvC:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp, @LucasLvy, and @stoobie)



<!-- Sent from Reviewable.io -->

2022-10-30 14:11 UTC, LucasLvy approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/91#-:-NFdDsHiDIE27DbyrP6V:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp and @stoobie)



<!-- Sent from Reviewable.io -->

2022-10-31 08:50 UTC, dan-ziv commented
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-91/documentation/ .

2022-10-31 09:07 UTC, stoobie reviewed
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/91)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @LucasLvy)

___
*[`components/StarkNet/modules/ROOT/pages/Ecosystem/ref_operational_info.adoc` line 20 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/91#-NFFcwkY4OwHd5ugbzh0:-NFhHRE67tX6UaSc0TYl:b-e6rw5z) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/a66d660d88fa43fbe35d07cd066543d6bd653a8d/components/StarkNet/modules/ROOT/pages/Ecosystem/ref_operational_info.adoc#L20)):*
<details><summary><i>Previously, LucasLvy (Lucas) wrote…</i></summary><blockquote>

A table to display everything on this page and not link to the json file
</blockquote></details>

Doing so creates a maintenance problem. I don't own the json file. If it's updated without me knowing, then this page that we're working on will become obsolete.


<!-- Sent from Reviewable.io -->

2022-10-31 09:17 UTC, glrn approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/91#-:-NFhKBQS0M2anYmKicGY:bnfp4nl)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @LucasLvy)



<!-- Sent from Reviewable.io -->

2022-10-31 09:29 UTC, stoobie reviewed
> Reviewed 1 of 2 files at r13, 8 of 8 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/91)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp, @bbrandtom, and @LucasLvy)



<!-- Sent from Reviewable.io -->

2022-10-31 09:30 UTC, merged

2022-10-31 13:51 UTC, glrn reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/91#-:-NFiIuII2MTbILHGhPSZ:bnfp4nl)* status: all files reviewed, 3 unresolved discussions



<!-- Sent from Reviewable.io -->